version: "2.35"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo


